<?php
/**
 * TL_ROOT/system/modules/ztheme_favorite/languages/de/default.php 
 * 
 * Contao extension: ztheme_favorite 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['helpview'] = "Hilfe";
$GLOBALS['TL_LANG']['MSC']['helpGlobal']['0'] = "Globale Aktionen";
$GLOBALS['TL_LANG']['MSC']['helpGlobal']['1'] = "In diesem Bereich können Sie die folgenden globalen Aktionen ausführen:";
$GLOBALS['TL_LANG']['MSC']['helpOperations']['0'] = "Aktionen";
$GLOBALS['TL_LANG']['MSC']['helpOperations']['1'] = "In diesem Bereich können Sie die folgenden speziellen Aktionen ausführen:";
$GLOBALS['TL_LANG']['MSC']['helpPending']['0'] = "Ausstehende Aktionen";
$GLOBALS['TL_LANG']['MSC']['helpPending']['1'] = "Sie müssen ausstehende Aktionen ausführen oder können diese unten abbrechen.";
$GLOBALS['TL_LANG']['MSC']['nohelp'] = "Eine Hilfe ist für diesen Bereich nicht verfügbar.";
$GLOBALS['TL_LANG']['MSC']['manageFavorites']['0'] = "[Verwalten]";
$GLOBALS['TL_LANG']['MSC']['manageFavorites']['1'] = "Verwalten Sie die Reihenfolge Ihrer Favoriten.";
$GLOBALS['TL_LANG']['MSC']['addFavorite']['0'] = "[Hinzufügen]";
$GLOBALS['TL_LANG']['MSC']['addFavorite']['1'] = "Fügen Sie einen Link zu Ihren Favoriten hinzu.";
$GLOBALS['TL_LANG']['MSC']['removeFavorite']['0'] = "[Entfernen]";
$GLOBALS['TL_LANG']['MSC']['removeFavorite']['1'] = "Entfernen Sie einen Link aus Ihren Favoriten.";
$GLOBALS['TL_LANG']['MSC']['fePreview'] = "Vorschau";
 
?>
