<?php
/**
 * TL_ROOT/system/modules/ztheme_favorite/languages/de/modules.php 
 * 
 * Contao extension: ztheme_favorite 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['favorite'] = "Favoriten";
$GLOBALS['TL_LANG']['MOD']['home']['0'] = "Startseite";
$GLOBALS['TL_LANG']['MOD']['home']['1'] = "Bitte wählen Sie eines der Module aus dem oberen Menü aus.<br><br>Erstellen Sie Seiten, fügen Sie Artikel hinzu, bearbeiten Sie Inhalte Ihrer Contao CMS Webseite.";
$GLOBALS['TL_LANG']['MOD']['accounts'] = "Benutzerkonten";
$GLOBALS['TL_LANG']['MOD']['profile'] = "Aktionen";
$GLOBALS['TL_LANG']['MOD']['page']['0'] = "Seiten";
$GLOBALS['TL_LANG']['MOD']['form']['0'] = "Formulare";
$GLOBALS['TL_LANG']['MOD']['files']['0'] = "Dateien";
$GLOBALS['TL_LANG']['MOD']['login']['0'] = "Profile";
$GLOBALS['TL_LANG']['MOD']['repository_catalog']['0'] = "Erweiterungen";
$GLOBALS['TL_LANG']['MOD']['repository_manager']['0'] = "Erweiterungsverwaltung";
$GLOBALS['TL_LANG']['MOD']['BackupDB']['0'] = "Datensicherung";
$GLOBALS['TL_LANG']['MOD']['updatedb']['0'] = "Datenbank aktualisieren";
$GLOBALS['TL_LANG']['MOD']['isotope'] = "Isotope";
$GLOBALS['TL_LANG']['MOD']['iso_products']['0'] = "Produkte";
$GLOBALS['TL_LANG']['MOD']['iso_products']['1'] = "Verwalten Sie Produkte, Varianten, Gruppen und importieren Sie Bilddateien.";
$GLOBALS['TL_LANG']['MOD']['iso_orders']['0'] = "Bestellungen";
$GLOBALS['TL_LANG']['MOD']['iso_orders']['1'] = "Bearbeiten oder drucken Sie Bestellungen und sehen Sie Zahlungs- und Versandinformationen an.";
$GLOBALS['TL_LANG']['MOD']['iso_rules']['0'] = "Regeln";
$GLOBALS['TL_LANG']['MOD']['iso_rules']['1'] = "Erstellen und verwalten Sie Regeln für Produkte oder Warenkörbe für Rabatte, Aktionszeiträume, Staffelpreise und Gutscheine.";
$GLOBALS['TL_LANG']['MOD']['iso_setup']['0'] = "Store-Konfiguration.";
$GLOBALS['TL_LANG']['MOD']['iso_setup']['1'] = "Erstellen und verwalten Sie Store-Konfigurationen für Produkttypen, Attribute, verwandte Kategorien, Zahlungs- und Versandarten, Steuern und E-Mail-Benachrichtigungen.";
$GLOBALS['TL_LANG']['TABLE']['tl_content']['0'] = "Inhaltselemente";
$GLOBALS['TL_LANG']['TABLE']['tl_content']['1'] = "Erstellen und verwalten Sie Inhaltselemente wie Texte, Bilder, Galerien, Tabellen, etc.";
$GLOBALS['TL_LANG']['TABLE']['tl_style_sheet']['0'] = "Stylesheets";
$GLOBALS['TL_LANG']['TABLE']['tl_style_sheet']['1'] = "Erstellen und verwalten Sie Stylesheets, um die Ausgabe im Frontend Ihrer Webseite zu formatieren.";
$GLOBALS['TL_LANG']['TABLE']['tl_style']['0'] = "Stile";
$GLOBALS['TL_LANG']['TABLE']['tl_style']['1'] = "Erstellen und verwalten Sie individuelle CSS-Stile innerhalb eines Stylesheets.";
$GLOBALS['TL_LANG']['TABLE']['tl_module']['0'] = "Module";
$GLOBALS['TL_LANG']['TABLE']['tl_module']['1'] = "Erstellen und verwalten Sie die Frontend-Module Ihrer Webseite.";
$GLOBALS['TL_LANG']['TABLE']['tl_layout']['0'] = "Layouts";
$GLOBALS['TL_LANG']['TABLE']['tl_layout']['1'] = "Kombinieren Sie Module und Stylesheets zu Ihrem Seitenlayout.";
$GLOBALS['TL_LANG']['TABLE']['tl_news']['0'] = "Nachrichten";
$GLOBALS['TL_LANG']['TABLE']['tl_news']['1'] = "Verwalten, publizieren und favorisieren Sie News-Artikel nach Datum.";
$GLOBALS['TL_LANG']['TABLE']['tl_calendar_events']['0'] = "Termine";
$GLOBALS['TL_LANG']['TABLE']['tl_calendar_events']['1'] = "Verwalten, publizieren oder favorisieren Sie Termine.";
$GLOBALS['TL_LANG']['TABLE']['tl_form_field']['0'] = "Formulare";
$GLOBALS['TL_LANG']['TABLE']['tl_form_field']['1'] = "Verwalten und publizieren Sie Teste, Textfelder, Select-Boxen, Radiobuttons, Checkboxen, Captchas und Absende-Buttons.";
$GLOBALS['TL_LANG']['TABLE']['tl_newsletter_recipients']['0'] = "Empfänger";
$GLOBALS['TL_LANG']['TABLE']['tl_newsletter_recipients']['1'] = "Importieren, verwalten und aktivieren Sie Newsletter-Empfänger.";
$GLOBALS['TL_LANG']['TABLE']['tl_newsletter']['0'] = "Newsletter";
$GLOBALS['TL_LANG']['TABLE']['tl_newsletter']['1'] = "Verwalten, publizieren und senden Sie Newsletter.";
$GLOBALS['TL_LANG']['TABLE']['tl_faq']['0'] = "FAQ";
$GLOBALS['TL_LANG']['TABLE']['tl_faq']['1'] = "Verwalten, publizieren und favorisieren Sie FAQ-Artikel.";
$GLOBALS['TL_LANG']['TABLE']['tl_glossary']['0'] = "Glossare";
$GLOBALS['TL_LANG']['TABLE']['tl_glossary']['1'] = "Verwalten, publizieren und favorisieren Sie Artikel für ein Glossar.";
$GLOBALS['TL_LANG']['TABLE']['tl_user_fav']['0'] = "Favoriten";
$GLOBALS['TL_LANG']['TABLE']['tl_user_fav']['1'] = "Verwalten Sie Ihr Favoriten-Menü.";
$GLOBALS['TL_LANG']['TABLE']['tl_gallery']['0'] = "Galeriebilder";
$GLOBALS['TL_LANG']['TABLE']['tl_gallery']['1'] = "Verwalten, publizieren und favorisieren Sie Bild-Galerien.";
$GLOBALS['TL_LANG']['TABLE']['tl_invitation']['0'] = "Einladungs-Mails";
$GLOBALS['TL_LANG']['TABLE']['tl_invitation']['1'] = "Verwalten, publizieren und senden Sie Einladungs-Mails.";
$GLOBALS['TL_LANG']['TABLE']['tl_zad_sendnews_rule']['0'] = "Sende-Regeln";
$GLOBALS['TL_LANG']['TABLE']['tl_zad_sendnews_rule']['1'] = "Verwalten Sie Regeln für News.";
$GLOBALS['TL_LANG']['TABLE']['tl_simplepoll_option']['0'] = "Abstimmungs-Optionen";
$GLOBALS['TL_LANG']['TABLE']['tl_simplepoll_option']['1'] = "Verwalten Sie die Optionen für Abstimmungen.";
$GLOBALS['TL_LANG']['MSC']['help'] = "Hilfe";
$GLOBALS['TL_LANG']['MSC']['nohelp'] = "Eine Hilfe ist für diesen Bereich nicht verfügbar.";
 
?>
