<?php
/**
 * TL_ROOT/system/modules/ztheme_favorite/languages/de/tl_user_fav.php 
 * 
 * Contao extension: ztheme_favorite 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_fav']['label']['0'] = "Beschriftung";
$GLOBALS['TL_LANG']['tl_user_fav']['label']['1'] = "Geben Sie die Beschriftung für den Favoriten ein.";
$GLOBALS['TL_LANG']['tl_user_fav']['url']['0'] = "Weiterleitungsziel";
$GLOBALS['TL_LANG']['tl_user_fav']['url']['1'] = "Geben Sie den Weiterleitungslink für Ihren Favoriten ein.";
$GLOBALS['TL_LANG']['tl_user_fav']['text']['0'] = "Hilfetext";
$GLOBALS['TL_LANG']['tl_user_fav']['text']['1'] = "Geben Sie den Hilfetext oder den Titel des Pop-Ups ein,";
$GLOBALS['TL_LANG']['tl_user_fav']['singleSRC']['0'] = "Favoriten-Icon";
$GLOBALS['TL_LANG']['tl_user_fav']['singleSRC']['1'] = "Bitte wählen Sie eine Bilddatei aus, um ein individuelles Symbolbild zu erstellen.";
$GLOBALS['TL_LANG']['tl_user_fav']['cssClass']['0'] = "CSS-Klasse";
$GLOBALS['TL_LANG']['tl_user_fav']['cssClass']['1'] = "Hier können Sie eine oder mehrere CSS-Klassen angeben.";
$GLOBALS['TL_LANG']['tl_user_fav']['published']['0'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_user_fav']['published']['1'] = "Machen Sie Ihren Favoriten sichtbar.";
$GLOBALS['TL_LANG']['tl_user_fav']['title_legend'] = "Titel, Weiterleitung und Symbolbild.";
$GLOBALS['TL_LANG']['tl_user_fav']['expert_legend'] = "Experteneinstellungen";
$GLOBALS['TL_LANG']['tl_user_fav']['publish_legend'] = "Veröffentlichungs-Einstellungen";
$GLOBALS['TL_LANG']['tl_user_fav']['new']['0'] = "Favoriten hinzufügen";
$GLOBALS['TL_LANG']['tl_user_fav']['new']['1'] = "Fügen Sie einen neuen Favoriten hinzu.";
$GLOBALS['TL_LANG']['tl_user_fav']['show']['0'] = "Favoriten-Details";
$GLOBALS['TL_LANG']['tl_user_fav']['show']['1'] = "Zeigt die Details Ihres Favoriten mit der ID %s.";
$GLOBALS['TL_LANG']['tl_user_fav']['edit']['0'] = "Favoriten bearbeiten";
$GLOBALS['TL_LANG']['tl_user_fav']['edit']['1'] = "Bearbeiten Sie den favoriten mit der ID %s.";
$GLOBALS['TL_LANG']['tl_user_fav']['copy']['0'] = "Favoriten duplizieren";
$GLOBALS['TL_LANG']['tl_user_fav']['copy']['1'] = "Duplizieren Sie den Favoriten mit der ID %s.";
$GLOBALS['TL_LANG']['tl_user_fav']['cut']['0'] = "Favoriten bewegen";
$GLOBALS['TL_LANG']['tl_user_fav']['cut']['1'] = "Bewegen Sie den Favoriten mit der ID %s.";
$GLOBALS['TL_LANG']['tl_user_fav']['delete']['0'] = "Favoriten löschen";
$GLOBALS['TL_LANG']['tl_user_fav']['delete']['1'] = "Löschen Sie den Favoriten mit der ID %s.";
$GLOBALS['TL_LANG']['tl_user_fav']['editheader']['0'] = "Nutzerprofil bearbeiten";
$GLOBALS['TL_LANG']['tl_user_fav']['editheader']['1'] = "Bearbeiten Sie das Nutzerprofil.";
$GLOBALS['TL_LANG']['tl_user_fav']['toggle']['0'] = "Favoriten veröffentlichen oder verstecken";
$GLOBALS['TL_LANG']['tl_user_fav']['toggle']['1'] = "Veröffentlichen oder verstecken Sie den Favoriten mit der ID %s.";
 
?>
