<?php
/**
 * TL_ROOT/system/modules/ztheme_favorite/languages/de/tl_user.php 
 * 
 * Contao extension: ztheme_favorite 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['favlock']['0'] = "Favoriten schützen";
$GLOBALS['TL_LANG']['tl_user']['favlock']['1'] = "Sperren Sie Ihre Favoriten für Aktionen wie hinzufügen und löschen.";
$GLOBALS['TL_LANG']['tl_user']['favdefault']['0'] = "Favoritenseite als Startseite setzen";
$GLOBALS['TL_LANG']['tl_user']['favdefault']['1'] = "Setzen Sie Ihren ersten Favoritenlink als Startseite. WARNUNG: benutzen Sie diese Funktion auf eigenes Risiko.";
$GLOBALS['TL_LANG']['tl_user']['favdisable']['0'] = "Favoriten deaktivieren";
$GLOBALS['TL_LANG']['tl_user']['favdisable']['1'] = "Entfernt 'Favoriten' aus der Navigation.";
$GLOBALS['TL_LANG']['tl_user']['favorite_legend'] = "Favoriten-Einstellungen";
$GLOBALS['TL_LANG']['tl_user']['favorites']['0'] = "Favoriten bearbeiten";
$GLOBALS['TL_LANG']['tl_user']['favorites']['1'] = "Bearbeiten Sie die Favoriten für den Benutzer mit der ID %s.";
 
?>
