<?php
/**
 * TL_ROOT/system/modules/ztheme_favorite/languages/de/tl_user_group.php 
 * 
 * Contao extension: ztheme_favorite 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_group']['favorite_legend'] = "Favoriten-Einstellungen";
 
?>
